version: "3"

services:
  dev:
    image: jekyll/jekyll:4
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll

  build:
    image: jekyll/jekyll:4
    command: jekyll build
    volumes:
      - .:/srv/jekyll

  clean:
    image: jekyll/jekyll:4
    command: jekyll clean
    volumes:
      - .:/srv/jekyll
